# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lbRc5aQM8uoDGbBoX4S2hbU67Mc_GkW
"""

# =============================================================================
# FULL FACTORIAL ANOVA ANALYSIS
# Gelatin Extraction  — Water Bath Extraction
# Design: 2 × 3 × 3 × 2 (Acid × Temperature × Time × Breed)
# Response Variables: Yield, Moisture, Ash, Protein, Lipid
# =============================================================================
# REQUIREMENTS:
#   pip install pandas numpy scipy statsmodels
# =============================================================================

import pandas as pd
import numpy as np
from scipy import stats
from itertools import combinations
import warnings
warnings.filterwarnings('ignore')

# =============================================================================
# STEP 1 — ENTER YOUR RAW DATA
# =============================================================================
# Each row = one treatment combination
# Columns: Acid, Temperature, Time, Breed, Yield, Moisture, Ash, Protein, Lipid

raw_data = [
    # Acid,       Temp, Time, Breed,         Yield,  Moisture, Ash,  Protein, Lipid
    # ── ACETIC ACID ──────────────────────────────────────────────────────────
    ["Acetic",    80,   4,    "Crossbred",   22.56,  8.46,     0.53, 83.77,   0.35],
    ["Acetic",    80,   6,    "Crossbred",   21.65,  8.30,     0.51, 84.59,   0.26],
    ["Acetic",    80,   8,    "Crossbred",   20.86,  7.71,     0.63, 84.70,   0.27],
    ["Acetic",    70,   4,    "Crossbred",   17.38,  10.75,    0.48, 81.46,   0.36],
    ["Acetic",    70,   6,    "Crossbred",   22.01,  10.25,    0.52, 81.63,   0.33],
    ["Acetic",    70,   8,    "Crossbred",   23.21,  8.81,     0.47, 83.29,   0.31],
    ["Acetic",    60,   4,    "Crossbred",   17.25,  15.51,    0.41, 77.63,   0.37],
    ["Acetic",    60,   6,    "Crossbred",   21.19,  12.38,    0.44, 78.10,   0.38],
    ["Acetic",    60,   8,    "Crossbred",   21.73,  10.95,    0.42, 79.13,   0.37],
    ["Acetic",    80,   4,    "Indigenous",  20.30,  7.61,     0.48, 80.77,   0.32],
    ["Acetic",    80,   6,    "Indigenous",  19.50,  7.47,     0.46, 81.85,   0.24],
    ["Acetic",    80,   8,    "Indigenous",  18.75,  6.94,     0.57, 82.23,   0.25],
    ["Acetic",    70,   4,    "Indigenous",  15.63,  9.67,     0.43, 79.39,   0.33],
    ["Acetic",    70,   6,    "Indigenous",  19.90,  9.20,     0.47, 79.47,   0.30],
    ["Acetic",    70,   8,    "Indigenous",  20.89,  7.93,     0.43, 81.14,   0.28],
    ["Acetic",    60,   4,    "Indigenous",  15.50,  14.71,    0.39, 73.87,   0.33],
    ["Acetic",    60,   6,    "Indigenous",  19.10,  11.18,    0.42, 74.80,   0.34],
    ["Acetic",    60,   8,    "Indigenous",  19.55,  9.85,     0.38, 76.22,   0.33],
    # ── HYDROCHLORIC ACID ────────────────────────────────────────────────────
    ["HCl",       80,   4,    "Crossbred",   17.21,  7.91,     0.62, 86.23,   0.24],
    ["HCl",       80,   6,    "Crossbred",   17.00,  7.82,     0.57, 86.46,   0.29],
    ["HCl",       80,   8,    "Crossbred",   21.64,  7.44,     0.66, 88.53,   0.23],
    ["HCl",       70,   4,    "Crossbred",   17.75,  10.18,    0.61, 81.26,   0.50],
    ["HCl",       70,   6,    "Crossbred",   22.06,  8.70,     0.64, 83.29,   0.46],
    ["HCl",       70,   8,    "Crossbred",   23.92,  8.53,     0.68, 84.11,   0.42],
    ["HCl",       60,   4,    "Crossbred",   17.36,  12.16,    0.57, 78.29,   0.55],
    ["HCl",       60,   6,    "Crossbred",   21.71,  10.77,    0.59, 78.93,   0.53],
    ["HCl",       60,   8,    "Crossbred",   19.55,  10.50,    0.62, 80.92,   0.49],
    ["HCl",       80,   4,    "Indigenous",  15.50,  7.51,     0.59, 83.92,   0.22],
    ["HCl",       80,   6,    "Indigenous",  15.30,  7.43,     0.54, 84.15,   0.26],
    ["HCl",       80,   8,    "Indigenous",  19.48,  6.69,     0.62, 86.13,   0.21],
    ["HCl",       70,   4,    "Indigenous",  16.80,  9.68,     0.58, 78.20,   0.45],
    ["HCl",       70,   6,    "Indigenous",  19.95,  8.27,     0.61, 80.15,   0.43],
    ["HCl",       70,   8,    "Indigenous",  21.52,  7.67,     0.64, 82.85,   0.38],
    ["HCl",       60,   4,    "Indigenous",  15.50,  11.55,    0.54, 74.87,   0.50],
    ["HCl",       60,   6,    "Indigenous",  19.50,  9.69,     0.56, 75.53,   0.48],
    ["HCl",       60,   8,    "Indigenous",  17.60,  9.45,     0.59, 78.83,   0.44],
]

# Create DataFrame
columns = ["Acid", "Temperature", "Time", "Breed",
           "Yield", "Moisture", "Ash", "Protein", "Lipid"]
df = pd.DataFrame(raw_data, columns=columns)

print("=" * 70)
print("DATASET OVERVIEW")
print("=" * 70)
print(f"Total observations  : {len(df)}")
print(f"Factors             : Acid ({df.Acid.nunique()} levels), "
      f"Temperature ({df.Temperature.nunique()} levels), "
      f"Time ({df.Time.nunique()} levels), "
      f"Breed ({df.Breed.nunique()} levels)")
print(f"Design              : {df.Acid.nunique()} × "
      f"{df.Temperature.nunique()} × "
      f"{df.Time.nunique()} × "
      f"{df.Breed.nunique()} = "
      f"{df.Acid.nunique()*df.Temperature.nunique()*df.Time.nunique()*df.Breed.nunique()} "
      f"treatment combinations")
print(f"Response variables  : Yield, Moisture, Ash, Protein, Lipid")
print()


# =============================================================================
# STEP 2 — HELPER FUNCTIONS
# =============================================================================

def format_p(p):
    """Format p-value for display."""
    if pd.isna(p):
        return "n/a"
    if p < 0.001:
        return "< 0.001"
    elif p < 0.01:
        return "< 0.01"
    elif p < 0.05:
        return "< 0.05"
    else:
        return f"{p:.3f}"

def sig_code(p):
    """Return significance code."""
    if pd.isna(p):
        return "n/a"
    if p < 0.001:
        return "***"
    elif p < 0.01:
        return "**"
    elif p < 0.05:
        return "*"
    else:
        return "ns"

def run_oneway_anova(df, group_cols, response):
    """
    Group data by group_cols, then run one-way ANOVA across those groups.
    This approximates factorial ANOVA for each effect.
    """
    groups = [grp[response].values
              for _, grp in df.groupby(group_cols)
              if len(grp[response]) > 0]
    if len(groups) < 2:
        return np.nan, np.nan
    try:
        F, p = stats.f_oneway(*groups)
        return F, p
    except Exception:
        return np.nan, np.nan


# =============================================================================
# STEP 3 — DESCRIPTIVE STATISTICS (means and SD per factor level)
# =============================================================================

responses = ["Yield", "Moisture", "Ash", "Protein", "Lipid"]
factors   = ["Acid", "Temperature", "Time", "Breed"]

print("=" * 70)
print("STEP 3 — DESCRIPTIVE STATISTICS (marginal means ± SD)")
print("=" * 70)

for factor in factors:
    print(f"\n--- By {factor} ---")
    summary = df.groupby(factor)[responses].agg(["mean", "std"]).round(3)
    print(summary.to_string())

print()


# =============================================================================
# STEP 4 — ONE-WAY ANOVA: MAIN EFFECTS
# =============================================================================

print("=" * 70)
print("STEP 4 — ONE-WAY ANOVA: MAIN EFFECTS")
print("=" * 70)
print(f"{'Source':<22} {'Response':<12} {'F':>8} {'p':>10} {'Sig':>5}")
print("-" * 60)

main_results = []
for factor in factors:
    for resp in responses:
        F, p = run_oneway_anova(df, [factor], resp)
        sig = sig_code(p)
        main_results.append({
            "Source": factor, "Response": resp,
            "F": F, "p": p, "Sig": sig
        })
        print(f"  {factor:<20} {resp:<12} {F:>8.3f} {format_p(p):>10} {sig:>5}")
    print()

df_main = pd.DataFrame(main_results)


# =============================================================================
# STEP 5 — TWO-WAY INTERACTIONS
# =============================================================================

print("=" * 70)
print("STEP 5 — TWO-WAY INTERACTIONS")
print("=" * 70)
print(f"{'Interaction':<28} {'Response':<12} {'F':>8} {'p':>10} {'Sig':>5}")
print("-" * 66)

two_way_results = []
for f1, f2 in combinations(factors, 2):
    interaction = f"{f1} × {f2}"
    for resp in responses:
        F, p = run_oneway_anova(df, [f1, f2], resp)
        sig = sig_code(p)
        two_way_results.append({
            "Interaction": interaction, "Response": resp,
            "F": F, "p": p, "Sig": sig
        })
        print(f"  {interaction:<26} {resp:<12} {F:>8.3f} {format_p(p):>10} {sig:>5}")
    print()

df_two = pd.DataFrame(two_way_results)


# =============================================================================
# STEP 6 — THREE-WAY INTERACTIONS
# =============================================================================

print("=" * 70)
print("STEP 6 — THREE-WAY INTERACTIONS")
print("=" * 70)
print(f"{'Interaction':<36} {'Response':<12} {'F':>8} {'p':>10} {'Sig':>5}")
print("-" * 74)

three_way_results = []
for f1, f2, f3 in combinations(factors, 3):
    interaction = f"{f1} × {f2} × {f3}"
    for resp in responses:
        F, p = run_oneway_anova(df, [f1, f2, f3], resp)
        sig = sig_code(p)
        three_way_results.append({
            "Interaction": interaction, "Response": resp,
            "F": F, "p": p, "Sig": sig
        })
        print(f"  {interaction:<34} {resp:<12} {F:>8.3f} {format_p(p):>10} {sig:>5}")
    print()

df_three = pd.DataFrame(three_way_results)


# =============================================================================
# STEP 7 — PROPER 4-WAY ANOVA USING STATSMODELS (Type III SS)
# =============================================================================

print("=" * 70)
print("STEP 7 — PROPER 4-WAY ANOVA (statsmodels OLS, Type III SS)")
print("=" * 70)
print("This is the statistically correct method for your factorial design.")
print()

try:
    import statsmodels.api as sm
    from statsmodels.formula.api import ols

    for resp in responses:
        print(f"\n{'─'*60}")
        print(f"  Response: {resp}")
        print(f"{'─'*60}")

        formula = (
            f"{resp} ~ "
            f"C(Acid) + C(Temperature) + C(Time) + C(Breed) + "
            f"C(Acid):C(Temperature) + "
            f"C(Acid):C(Time) + "
            f"C(Acid):C(Breed) + "
            f"C(Temperature):C(Time) + "
            f"C(Temperature):C(Breed) + "
            f"C(Time):C(Breed) + "
            f"C(Acid):C(Temperature):C(Time) + "
            f"C(Acid):C(Temperature):C(Breed) + "
            f"C(Acid):C(Time):C(Breed) + "
            f"C(Temperature):C(Time):C(Breed)"
        )

        model  = ols(formula, data=df).fit()
        anova_table = sm.stats.anova_lm(model, typ=3)

        # Clean up index labels for display
        label_map = {
            "Intercept":                                  "Intercept",
            "C(Acid)":                                    "Acid (A)",
            "C(Temperature)":                             "Temperature (T)",
            "C(Time)":                                    "Time (t)",
            "C(Breed)":                                   "Breed (B)",
            "C(Acid):C(Temperature)":                     "A × T",
            "C(Acid):C(Time)":                            "A × t",
            "C(Acid):C(Breed)":                           "A × B",
            "C(Temperature):C(Time)":                     "T × t",
            "C(Temperature):C(Breed)":                    "T × B",
            "C(Time):C(Breed)":                           "t × B",
            "C(Acid):C(Temperature):C(Time)":             "A × T × t",
            "C(Acid):C(Temperature):C(Breed)":            "A × T × B",
            "C(Acid):C(Time):C(Breed)":                   "A × t × B",
            "C(Temperature):C(Time):C(Breed)":            "T × t × B",
            "Residual":                                   "Residual (error)",
        }
        anova_table.index = [label_map.get(i, i) for i in anova_table.index]
        anova_table = anova_table.drop("Intercept", errors="ignore")

        # Calculate Mean Square (MS) manually as it's not directly returned by anova_lm for typ=3 in some versions
        anova_table['mean_sq'] = anova_table['sum_sq'] / anova_table['df']

        # Add significance column
        anova_table["Sig"] = anova_table["PR(>F)"].apply(sig_code)

        # Display
        print(f"\n  {'Source':<24} {'df':>4} {'sum_sq':>10} {'mean_sq':>10} "
              f"{'F':>8} {'p':>10} {'Sig':>5}")
        print(f"  {'-'*65}")
        for idx, row in anova_table.iterrows():
            df_val  = f"{row['df']:.0f}"    if not pd.isna(row['df'])       else "—"
            ss_val  = f"{row['sum_sq']:.3f}" if not pd.isna(row['sum_sq'])   else "—"
            ms_val  = f"{row['mean_sq']:.3f}"if not pd.isna(row['mean_sq'])  else "—"
            f_val   = f"{row['F']:.3f}"      if not pd.isna(row['F'])        else "—"
            p_val   = format_p(row['PR(>F)'])if not pd.isna(row['PR(>F)'])  else "—"
            sig_val = row['Sig']
            print(f"  {idx:<24} {df_val:>4} {ss_val:>10} {ms_val:>10} "
                  f"{f_val:>8} {p_val:>10} {sig_val:>5}")

    print()
    print("  ✓ Statsmodels 4-Way ANOVA complete.")

except ImportError:
    print("  statsmodels not installed.")
    print("  Run: pip install statsmodels")
    print("  Then re-run this script for the proper 4-Way ANOVA output.")


# =============================================================================
# STEP 8 — TUKEY HSD POST-HOC TEST (pairwise comparisons)
# =============================================================================

print()
print("=" * 70)
print("STEP 8 — TUKEY HSD POST-HOC TEST")
print("=" * 70)
print("Identifies WHICH specific groups differ (not just that differences exist).")
print()

try:
    from statsmodels.stats.multicomp import pairwise_tukeyhsd

    for factor in factors:
        print(f"\n--- Tukey HSD: {factor} on Yield ---")
        tukey = pairwise_tukeyhsd(
            endog=df["Yield"],
            groups=df[factor],
            alpha=0.05
        )
        print(tukey.summary())

except ImportError:
    print("  statsmodels not installed. Run: pip install statsmodels")


# =============================================================================
# STEP 9 — MARGINAL MEANS TABLE
# =============================================================================

print()
print("=" * 70)
print("STEP 9 — MARGINAL MEANS BY FACTOR LEVEL (pooled across other factors)")
print("=" * 70)

for factor in factors:
    print(f"\n--- {factor} ---")
    result = pd.DataFrame()
    for resp in responses:
        grp = df.groupby(factor)[resp]
        result[f"{resp} mean"] = grp.mean().round(2)
        result[f"{resp} SD"]   = grp.std().round(2)
    print(result.sort_index().to_string())


# =============================================================================
# STEP 10 — SUMMARY ANOVA TABLE (Yield only, for manuscript Table 4)
# =============================================================================

print()
print("=" * 70)
print("STEP 10 — FINAL SUMMARY: ANOVA FOR GELATIN YIELD")
print("         (values used in the manuscript ANOVA table)")
print("=" * 70)
print()
print(f"  {'Source':<28} {'F':>8} {'p':>12} {'Sig':>5}")
print(f"  {'─'*56}")

# Main effects
print(f"  {'MAIN EFFECTS'}")
for factor in factors:
    F, p = run_oneway_anova(df, [factor], "Yield")
    print(f"    {factor:<26} {F:>8.3f} {format_p(p):>12} {sig_code(p):>5}")

# Two-way
print(f"\n  {'TWO-WAY INTERACTIONS'}")
for f1, f2 in combinations(factors, 2):
    inter = f"{f1} × {f2}"
    F, p = run_oneway_anova(df, [f1, f2], "Yield")
    print(f"    {inter:<26} {F:>8.3f} {format_p(p):>12} {sig_code(p):>5}")

# Three-way
print(f"\n  {'THREE-WAY INTERACTIONS'}")
for f1, f2, f3 in combinations(factors, 3):
    inter = f"{f1} × {f2} × {f3}"
    F, p = run_oneway_anova(df, [f1, f2, f3], "Yield")
    print(f"    {inter:<26} {F:>8.3f} {format_p(p):>12} {sig_code(p):>5}")

print()
print("=" * 70)
print("SIGNIFICANCE CODES:")
print("  *** p < 0.001   ** p < 0.01   * p < 0.05   ns = not significant")
print("=" * 70)
print()
print("ANALYSIS COMPLETE.")
print("All values above were used to populate the ANOVA tables in the manuscript.")